
export const CREAT_ORDER_REQUEST = 'CREAT_ORDER_REQUEST';
export const CREAT_ORDER_SUCCESS = 'CREAT_ORDER_SUCCESS';
export const CREAT_ORDER_FAILURE = 'CREAT_ORDER_FAILURE';

export const GET_USERS_ORDERS_REQUEST = 'GET_USERS_ORDERS_REQUEST';
export const GET_USERS_ORDERS_SUCCESS = 'GET_USERS_ORDERS_SUCCESS';
export const GET_USERS_ORDERS_FAILURE = 'GET_USERS_ORDERS_FAILURE';

export const GET_USERS_MODIFICATION_REQUEST = 'GET_USERS_MODIFICATION_REQUEST';
export const GET_USERS_MODIFICATION_SUCCESS = 'GET_USERS_MODIFICATION_SUCCESS';
export const GET_USERS_MODIFICATION_FAILURE = 'GET_USERS_MODIFICATION_FAILURE';

export const UPDATE_CART_ITEM_QUANTITY_REQUEST = 'UPDATE_CART_ITEM_QUANTITY_REQUEST';
export const UPDATE_CART_ITEM_QUANTITY_SUCCESS = 'UPDATE_CART_ITEM_QUANTITY_SUCCESS';
export const UPDATE_CART_ITEM_QUANTITY_FAILURE = 'UPDATE_CART_ITEM_QUANTITY_FAILURE';
