
export const GET_RESTAURANTS_ORDER_REQUEST = 'GET_RESTAURANTS_ORDER_REQUEST';
export const GET_RESTAURANTS_ORDER_SUCCESS = 'GET_RESTAURANTS_ORDER_SUCCESS';
export const GET_RESTAURANTS_ORDER_FAILURE = 'GET_RESTAURANTS_ORDER_FAILURE';

export const UPADTE_ORDER_STATUS_REQUEST = 'UPADTE_ORDER_STATUS_REQUEST';
export const UPADTE_ORDER_STATUS_SUCCESS = 'UPADTE_ORDER_STATUS_SUCCESS';
export const UPADTE_ORDER_STATUS_FAILURE = 'UPADTE_ORDER_STATUS_FAILURE';